# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_autoscaling_v2_resource_metric_source import IoK8sApiAutoscalingV2ResourceMetricSource

class TestIoK8sApiAutoscalingV2ResourceMetricSource(unittest.TestCase):
    """IoK8sApiAutoscalingV2ResourceMetricSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiAutoscalingV2ResourceMetricSource:
        """Test IoK8sApiAutoscalingV2ResourceMetricSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiAutoscalingV2ResourceMetricSource`
        """
        model = IoK8sApiAutoscalingV2ResourceMetricSource()
        if include_optional:
            return IoK8sApiAutoscalingV2ResourceMetricSource(
                name = '',
                target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                    average_utilization = 56, 
                    average_value = '', 
                    type = '', 
                    value = '', )
            )
        else:
            return IoK8sApiAutoscalingV2ResourceMetricSource(
                name = '',
                target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                    average_utilization = 56, 
                    average_value = '', 
                    type = '', 
                    value = '', ),
        )
        """

    def testIoK8sApiAutoscalingV2ResourceMetricSource(self):
        """Test IoK8sApiAutoscalingV2ResourceMetricSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
