# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.jobset_v1alpha2_scale import JobsetV1alpha2Scale

class TestJobsetV1alpha2Scale(unittest.TestCase):
    """JobsetV1alpha2Scale unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobsetV1alpha2Scale:
        """Test JobsetV1alpha2Scale
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobsetV1alpha2Scale`
        """
        model = JobsetV1alpha2Scale()
        if include_optional:
            return JobsetV1alpha2Scale(
                auto_scaling = jobset.models.jobset_v1alpha2_auto_scaling.JobsetV1alpha2AutoScaling(
                    max_replicas = 56, 
                    metrics = [
                        jobset.models.io/k8s/api/autoscaling/v2/metric_spec.io.k8s.api.autoscaling.v2.MetricSpec(
                            container_resource = jobset.models.io/k8s/api/autoscaling/v2/container_resource_metric_source.io.k8s.api.autoscaling.v2.ContainerResourceMetricSource(
                                container = '', 
                                name = '', 
                                target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                                    average_utilization = 56, 
                                    average_value = '', 
                                    type = '', 
                                    value = '', ), ), 
                            external = jobset.models.io/k8s/api/autoscaling/v2/external_metric_source.io.k8s.api.autoscaling.v2.ExternalMetricSource(
                                metric = jobset.models.io/k8s/api/autoscaling/v2/metric_identifier.io.k8s.api.autoscaling.v2.MetricIdentifier(
                                    name = '', 
                                    selector = jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector(
                                        match_expressions = [
                                            jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector_requirement.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement(
                                                key = '', 
                                                operator = '', 
                                                values = [
                                                    ''
                                                    ], )
                                            ], 
                                        match_labels = {
                                            'key' : ''
                                            }, ), ), 
                                target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                                    average_utilization = 56, 
                                    type = '', ), ), 
                            object = jobset.models.io/k8s/api/autoscaling/v2/object_metric_source.io.k8s.api.autoscaling.v2.ObjectMetricSource(
                                described_object = jobset.models.io/k8s/api/autoscaling/v2/cross_version_object_reference.io.k8s.api.autoscaling.v2.CrossVersionObjectReference(
                                    api_version = '', 
                                    kind = '', 
                                    name = '', ), 
                                metric = jobset.models.io/k8s/api/autoscaling/v2/metric_identifier.io.k8s.api.autoscaling.v2.MetricIdentifier(
                                    name = '', ), 
                                target = , ), 
                            pods = jobset.models.io/k8s/api/autoscaling/v2/pods_metric_source.io.k8s.api.autoscaling.v2.PodsMetricSource(
                                metric = , 
                                target = , ), 
                            resource = jobset.models.io/k8s/api/autoscaling/v2/resource_metric_source.io.k8s.api.autoscaling.v2.ResourceMetricSource(
                                name = '', 
                                target = , ), 
                            type = '', )
                        ], 
                    min_replicas = 56, ),
                replicated_job_name = ''
            )
        else:
            return JobsetV1alpha2Scale(
                auto_scaling = jobset.models.jobset_v1alpha2_auto_scaling.JobsetV1alpha2AutoScaling(
                    max_replicas = 56, 
                    metrics = [
                        jobset.models.io/k8s/api/autoscaling/v2/metric_spec.io.k8s.api.autoscaling.v2.MetricSpec(
                            container_resource = jobset.models.io/k8s/api/autoscaling/v2/container_resource_metric_source.io.k8s.api.autoscaling.v2.ContainerResourceMetricSource(
                                container = '', 
                                name = '', 
                                target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                                    average_utilization = 56, 
                                    average_value = '', 
                                    type = '', 
                                    value = '', ), ), 
                            external = jobset.models.io/k8s/api/autoscaling/v2/external_metric_source.io.k8s.api.autoscaling.v2.ExternalMetricSource(
                                metric = jobset.models.io/k8s/api/autoscaling/v2/metric_identifier.io.k8s.api.autoscaling.v2.MetricIdentifier(
                                    name = '', 
                                    selector = jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector(
                                        match_expressions = [
                                            jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector_requirement.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement(
                                                key = '', 
                                                operator = '', 
                                                values = [
                                                    ''
                                                    ], )
                                            ], 
                                        match_labels = {
                                            'key' : ''
                                            }, ), ), 
                                target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                                    average_utilization = 56, 
                                    type = '', ), ), 
                            object = jobset.models.io/k8s/api/autoscaling/v2/object_metric_source.io.k8s.api.autoscaling.v2.ObjectMetricSource(
                                described_object = jobset.models.io/k8s/api/autoscaling/v2/cross_version_object_reference.io.k8s.api.autoscaling.v2.CrossVersionObjectReference(
                                    api_version = '', 
                                    kind = '', 
                                    name = '', ), 
                                metric = jobset.models.io/k8s/api/autoscaling/v2/metric_identifier.io.k8s.api.autoscaling.v2.MetricIdentifier(
                                    name = '', ), 
                                target = , ), 
                            pods = jobset.models.io/k8s/api/autoscaling/v2/pods_metric_source.io.k8s.api.autoscaling.v2.PodsMetricSource(
                                metric = , 
                                target = , ), 
                            resource = jobset.models.io/k8s/api/autoscaling/v2/resource_metric_source.io.k8s.api.autoscaling.v2.ResourceMetricSource(
                                name = '', 
                                target = , ), 
                            type = '', )
                        ], 
                    min_replicas = 56, ),
                replicated_job_name = '',
        )
        """

    def testJobsetV1alpha2Scale(self):
        """Test JobsetV1alpha2Scale"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
