# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.jobset_v1alpha2_scale_policy import JobsetV1alpha2ScalePolicy

class TestJobsetV1alpha2ScalePolicy(unittest.TestCase):
    """JobsetV1alpha2ScalePolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobsetV1alpha2ScalePolicy:
        """Test JobsetV1alpha2ScalePolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobsetV1alpha2ScalePolicy`
        """
        model = JobsetV1alpha2ScalePolicy()
        if include_optional:
            return JobsetV1alpha2ScalePolicy(
                replicated_job = ''
            )
        else:
            return JobsetV1alpha2ScalePolicy(
                replicated_job = '',
        )
        """

    def testJobsetV1alpha2ScalePolicy(self):
        """Test JobsetV1alpha2ScalePolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
