# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_autoscaling_v2_cross_version_object_reference import IoK8sApiAutoscalingV2CrossVersionObjectReference

class TestIoK8sApiAutoscalingV2CrossVersionObjectReference(unittest.TestCase):
    """IoK8sApiAutoscalingV2CrossVersionObjectReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiAutoscalingV2CrossVersionObjectReference:
        """Test IoK8sApiAutoscalingV2CrossVersionObjectReference
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiAutoscalingV2CrossVersionObjectReference`
        """
        model = IoK8sApiAutoscalingV2CrossVersionObjectReference()
        if include_optional:
            return IoK8sApiAutoscalingV2CrossVersionObjectReference(
                api_version = '',
                kind = '',
                name = ''
            )
        else:
            return IoK8sApiAutoscalingV2CrossVersionObjectReference(
                kind = '',
                name = '',
        )
        """

    def testIoK8sApiAutoscalingV2CrossVersionObjectReference(self):
        """Test IoK8sApiAutoscalingV2CrossVersionObjectReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
