# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_autoscaling_v2_metric_spec import IoK8sApiAutoscalingV2MetricSpec

class TestIoK8sApiAutoscalingV2MetricSpec(unittest.TestCase):
    """IoK8sApiAutoscalingV2MetricSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiAutoscalingV2MetricSpec:
        """Test IoK8sApiAutoscalingV2MetricSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiAutoscalingV2MetricSpec`
        """
        model = IoK8sApiAutoscalingV2MetricSpec()
        if include_optional:
            return IoK8sApiAutoscalingV2MetricSpec(
                container_resource = jobset.models.io/k8s/api/autoscaling/v2/container_resource_metric_source.io.k8s.api.autoscaling.v2.ContainerResourceMetricSource(
                    container = '', 
                    name = '', 
                    target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                        average_utilization = 56, 
                        average_value = '', 
                        type = '', 
                        value = '', ), ),
                external = jobset.models.io/k8s/api/autoscaling/v2/external_metric_source.io.k8s.api.autoscaling.v2.ExternalMetricSource(
                    metric = jobset.models.io/k8s/api/autoscaling/v2/metric_identifier.io.k8s.api.autoscaling.v2.MetricIdentifier(
                        name = '', 
                        selector = jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector(
                            match_expressions = [
                                jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector_requirement.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), ), 
                    target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                        average_utilization = 56, 
                        average_value = '', 
                        type = '', 
                        value = '', ), ),
                object = jobset.models.io/k8s/api/autoscaling/v2/object_metric_source.io.k8s.api.autoscaling.v2.ObjectMetricSource(
                    described_object = jobset.models.io/k8s/api/autoscaling/v2/cross_version_object_reference.io.k8s.api.autoscaling.v2.CrossVersionObjectReference(
                        api_version = '', 
                        kind = '', 
                        name = '', ), 
                    metric = jobset.models.io/k8s/api/autoscaling/v2/metric_identifier.io.k8s.api.autoscaling.v2.MetricIdentifier(
                        name = '', 
                        selector = jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector(
                            match_expressions = [
                                jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector_requirement.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), ), 
                    target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                        average_utilization = 56, 
                        average_value = '', 
                        type = '', 
                        value = '', ), ),
                pods = jobset.models.io/k8s/api/autoscaling/v2/pods_metric_source.io.k8s.api.autoscaling.v2.PodsMetricSource(
                    metric = jobset.models.io/k8s/api/autoscaling/v2/metric_identifier.io.k8s.api.autoscaling.v2.MetricIdentifier(
                        name = '', 
                        selector = jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector(
                            match_expressions = [
                                jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector_requirement.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), ), 
                    target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                        average_utilization = 56, 
                        average_value = '', 
                        type = '', 
                        value = '', ), ),
                resource = jobset.models.io/k8s/api/autoscaling/v2/resource_metric_source.io.k8s.api.autoscaling.v2.ResourceMetricSource(
                    name = '', 
                    target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                        average_utilization = 56, 
                        average_value = '', 
                        type = '', 
                        value = '', ), ),
                type = ''
            )
        else:
            return IoK8sApiAutoscalingV2MetricSpec(
                type = '',
        )
        """

    def testIoK8sApiAutoscalingV2MetricSpec(self):
        """Test IoK8sApiAutoscalingV2MetricSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
