# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_autoscaling_v2_metric_identifier import IoK8sApiAutoscalingV2MetricIdentifier

class TestIoK8sApiAutoscalingV2MetricIdentifier(unittest.TestCase):
    """IoK8sApiAutoscalingV2MetricIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiAutoscalingV2MetricIdentifier:
        """Test IoK8sApiAutoscalingV2MetricIdentifier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiAutoscalingV2MetricIdentifier`
        """
        model = IoK8sApiAutoscalingV2MetricIdentifier()
        if include_optional:
            return IoK8sApiAutoscalingV2MetricIdentifier(
                name = '',
                selector = jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector(
                    match_expressions = [
                        jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector_requirement.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement(
                            key = '', 
                            operator = '', 
                            values = [
                                ''
                                ], )
                        ], 
                    match_labels = {
                        'key' : ''
                        }, )
            )
        else:
            return IoK8sApiAutoscalingV2MetricIdentifier(
                name = '',
        )
        """

    def testIoK8sApiAutoscalingV2MetricIdentifier(self):
        """Test IoK8sApiAutoscalingV2MetricIdentifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
