# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_autoscaling_v2_external_metric_source import IoK8sApiAutoscalingV2ExternalMetricSource

class TestIoK8sApiAutoscalingV2ExternalMetricSource(unittest.TestCase):
    """IoK8sApiAutoscalingV2ExternalMetricSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiAutoscalingV2ExternalMetricSource:
        """Test IoK8sApiAutoscalingV2ExternalMetricSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiAutoscalingV2ExternalMetricSource`
        """
        model = IoK8sApiAutoscalingV2ExternalMetricSource()
        if include_optional:
            return IoK8sApiAutoscalingV2ExternalMetricSource(
                metric = jobset.models.io/k8s/api/autoscaling/v2/metric_identifier.io.k8s.api.autoscaling.v2.MetricIdentifier(
                    name = '', 
                    selector = jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector(
                        match_expressions = [
                            jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector_requirement.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement(
                                key = '', 
                                operator = '', 
                                values = [
                                    ''
                                    ], )
                            ], 
                        match_labels = {
                            'key' : ''
                            }, ), ),
                target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                    average_utilization = 56, 
                    average_value = '', 
                    type = '', 
                    value = '', )
            )
        else:
            return IoK8sApiAutoscalingV2ExternalMetricSource(
                metric = jobset.models.io/k8s/api/autoscaling/v2/metric_identifier.io.k8s.api.autoscaling.v2.MetricIdentifier(
                    name = '', 
                    selector = jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector(
                        match_expressions = [
                            jobset.models.io/k8s/apimachinery/pkg/apis/meta/v1/label_selector_requirement.io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement(
                                key = '', 
                                operator = '', 
                                values = [
                                    ''
                                    ], )
                            ], 
                        match_labels = {
                            'key' : ''
                            }, ), ),
                target = jobset.models.io/k8s/api/autoscaling/v2/metric_target.io.k8s.api.autoscaling.v2.MetricTarget(
                    average_utilization = 56, 
                    average_value = '', 
                    type = '', 
                    value = '', ),
        )
        """

    def testIoK8sApiAutoscalingV2ExternalMetricSource(self):
        """Test IoK8sApiAutoscalingV2ExternalMetricSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
