/*
Copyright 2023 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// ScaleApplyConfiguration represents a declarative configuration of the Scale type for use
// with apply.
type ScaleApplyConfiguration struct {
	ReplicatedJobName *string `json:"replicatedJobName,omitempty"`
}

// ScaleApplyConfiguration constructs a declarative configuration of the Scale type for use with
// apply.
func Scale() *ScaleApplyConfiguration {
	return &ScaleApplyConfiguration{}
}

// WithReplicatedJobName sets the ReplicatedJobName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplicatedJobName field is set to the value of the last call.
func (b *ScaleApplyConfiguration) WithReplicatedJobName(value string) *ScaleApplyConfiguration {
	b.ReplicatedJobName = &value
	return b
}
