/*
Copyright 2023 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// ScalePolicyApplyConfiguration represents a declarative configuration of the ScalePolicy type for use
// with apply.
type ScalePolicyApplyConfiguration struct {
	ReplicatedJob *string `json:"replicatedJob,omitempty"`
}

// ScalePolicyApplyConfiguration constructs a declarative configuration of the ScalePolicy type for use with
// apply.
func ScalePolicy() *ScalePolicyApplyConfiguration {
	return &ScalePolicyApplyConfiguration{}
}

// WithReplicatedJob sets the ReplicatedJob field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplicatedJob field is set to the value of the last call.
func (b *ScalePolicyApplyConfiguration) WithReplicatedJob(value string) *ScalePolicyApplyConfiguration {
	b.ReplicatedJob = &value
	return b
}
